theme: jekyll-theme-cayman
# permalink: /LittleRatura/:categories/:year/:month/:day/:title/
google_analytics: UA-139881326-1
lang: cs-CZ

docs_list_title: ACME Documentation
docs:
  - title: LittleLatura
    url: /LittleRatura/index.html

  - title: Knížky
    url: /LittleRatura/post-naviagtion.html

  - title: ShowOff
    url: /LittleRatura/showOff.html
